POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "hssndev09",
  "password": "123123123"
}

###

GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1bmllbDExMSIsInN1YiI6IjY3ZWNhZTkyNzZiZmIwNjJhZDFkMjc1ZSIsImlhdCI6MTc0MzU3ODI3NSwiZXhwIjoxNzQzNjY0Njc1fQ.hwCvqqrXtO8j_J_L4FsNLR3lTcghCSigU01P4mGcHvo


###

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Juniel Husain",
  "username": "juniel111",
  "password": "changeme",
  "email": "john@gmail.com"
}

###
PATCH http://localhost:3000/users/67eb6e3e51de151382880ec3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1bmllbDk5OSIsInN1YiI6IjY3ZWI2ZTNlNTFkZTE1MTM4Mjg4MGVjMyIsImlhdCI6MTc0MzQ4NDY5NCwiZXhwIjoxNzQzNTcxMDk0fQ.2xfFaK9z9rxmUd77ypHIU_MU0IDa6rOaRHz77s5cQoE
Content-Type: application/json


{
  "name": "Juniel Gwapo",
  "username": "juniel999",
  "password": "changeme",
  "email": "john@gmail.com"
}