GET http://localhost:3000/tasks

###

# Create a task
POST http://localhost:3000/tasks HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1bmllbDExMSIsInN1YiI6IjY3ZWNhZTkyNzZiZmIwNjJhZDFkMjc1ZSIsImlhdCI6MTc0MzU3NTY1NiwiZXhwIjoxNzQzNjYyMDU2fQ.EbGld08jinxtcRA8CnYz1OT_S3xZz3Zc-HCcB9V0no0

{
  "title": "task with a timestamp",
  "description": "task with a timestamp"
}

### 

# Get all User tasks
GET http://localhost:3000/users/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1bmllbDAwMCIsInN1YiI6IjY3ZWI5YjA4Y2M1Nzc2OTkwODI5M2E2NyIsImlhdCI6MTc0MzQ5MzkwMCwiZXhwIjoxNzQzNTgwMzAwfQ.SJRIey-gr3O4SmqJ1bxjdjTkw9DfyejbQXMJViBZRXc


###
# Update a task
PATCH http://localhost:3000/tasks/67ecda7a8fb2b5cd37eb47ee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1bmllbDExMSIsInN1YiI6IjY3ZWNhZTkyNzZiZmIwNjJhZDFkMjc1ZSIsImlhdCI6MTc0MzU3NTY1NiwiZXhwIjoxNzQzNjYyMDU2fQ.EbGld08jinxtcRA8CnYz1OT_S3xZz3Zc-HCcB9V0no0
Content-Type: application/json

{
  "description": "gfdffdgfd",
  "isComplete": true,
  "status": "pending"
}

###