GET http://localhost:3000/tasks

###

# Create a task
POST http://localhost:3000/tasks HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imhzc25kZXYwOSIsInN1YiI6IjY3ZjQwN2RkOTQ0N2I0NTY2MzNjZjRmMiIsImlhdCI6MTc0NDA0NjA2MiwiZXhwIjoxNzQ0MTMyNDYyfQ.5jurwezutIctRFyqNvIdN4OhikPDBe3WrRSxufDkL1Q

{
  "title": "fix bugs in frontend",
  "description": "finish the bugs in angular frontend project"
}

### 

# Get all User tasks
GET http://localhost:3000/users/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imhzc25kZXYwOSIsInN1YiI6IjY3ZjQwN2RkOTQ0N2I0NTY2MzNjZjRmMiIsImlhdCI6MTc0NDA3Mjk5OCwiZXhwIjoxNzQ0MTU5Mzk4fQ.H8JANylKR2yFyV38EgE2cbUD3tRhbFYJDNU5dIdOtN8


###
# Update a task
PATCH http://localhost:3000/tasks/67f408449447b456633cf4f5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imhzc25kZXYwOSIsInN1YiI6IjY3ZjQwN2RkOTQ0N2I0NTY2MzNjZjRmMiIsImlhdCI6MTc0NDA3Mjk5OCwiZXhwIjoxNzQ0MTU5Mzk4fQ.H8JANylKR2yFyV38EgE2cbUD3tRhbFYJDNU5dIdOtN8
Content-Type: application/json

{
  "title": "finish backend logs in routes",
  "status": "pending"
}

###